package com.promotionproject.dao;

import com.promotionproject.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderRecord
     *
     * @mbg.generated Mon Feb 15 18:44:07 CST 2021
     */
    int updateByPrimaryKey(OrderDO record);
}